server:
  port: 9094
spring:
  application:
    name: BankAppllication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ajaymysql
    url: jdbc:mysql://localhost:3306/bank_application
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
